name: .NET Framework Build on Windows

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: msbuild /t:restore

      - name: Build project
        run: msbuild /p:Configuration=Release /p:TargetFrameworkVersion=v4.8 /p:RestorePackagesConfig=true

      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: |
            **/bin/Release/**
